### ISSUE TITLE
[Meta] Have you seen the existing graphql_parser, graphql*, etc. libraries?

### ISSUE THREAD

**Issue by thosakwe** [gql-dart/gql#1]
Hello, Klavs! I saw this pop up on my Github feed. If you didn't know, I have existing GraphQL parser/schema/introspection/server libraries here: https://github.com/angel-dart/graphql

It may be easier in the long run to join that project and contribute there.

Of course, though, it is your choice, and completely up to you.

**Comment by klavs** [comment]
Hi @thosakwe,

I am aware of your work on `graphql_parser` and I've taken a tiny bit of inspiration from it. To be fair, I've noticed that it's docs are highly misleading as it is not compatible with the latest GraphQL spec and it is not implementing the Visitor Pattern (as suggested in readme file).

This project really started as my pet project to better understand GraphQL spec, but it unexpectedly grew into the most up-to-spec GraphQL parser for Dart ecosystem. So I had to share my work.

Due to it's current state and our different approaches in source parsing, I do not really see how my work can benefit your's other than to replace it as a major version update.

My goal is to make it easy to write tooling for GraphQL so my focus is on parsing, transformation and printing (validation coming up later). I am not interested in execution of GraphQL Documents.

If you are interested in taking your packages to the latest version of the GraphQL spec, consider using this parser. Feel free to contribute by filing issues and creating Pull Requests.

My current plan is to improve test coverage. After that is done, I'll publish `0.1.0` version.

**Comment by thosakwe** [comment]
Ah, I see what you mean now. `graphql_parser` is not misleading in its docs (it is up to date with the June 2018 spec), it's just that it only parses queries - not the schema language (because it expects these to be defined in Dart). There's also no explicit mention of the visitor pattern, but the AST visiting logic was actually moved to `graphql_server`. So "misleading" isn't exactly the word I would use.

But I understand. Good luck with this project. No hard feelings.

**Comment by thosakwe** [comment]
As of version `2.0.0-beta`, both `graphql_server` and `angel_graphql` are using the `package:gql` parser. I intend to deprecate `graphql_parser` entirely.

https://pub.dev/packages/graphql_server/versions/2.0.0-beta

**Comment by klavs** [comment]
@thosakwe, thanks for the info!

I'll add your packages to the users list in the readme.
