### ISSUE TITLE
[gql_websocket_link] Release 0.3.1?

### ISSUE THREAD

**Issue by shyndman** [gql-dart/gql#233]
Hi there,

I was wondering if you'd consider release a 0.3.1 stable? The multi-channel issue fixed by #230 resulted in significantly improved stability for some users of nhost-dart. I'd like to re-release our packages with the new version.

**Comment by agent3bood** [comment]
@klavs   @smkhalsa Can you have a look at this, I have merged 0.3.1 into master but it did not get published to pub.

**Comment by smkhalsa** [comment]
> but it did not get published to pub

@agent3bood it was published, just as an [alpha](https://pub.dev/packages/gql_websocket_link/versions/0.3.2-alpha+1621584656268) release, right? It seems @shyndman is requesting a stable release so that he can publish stable versions of his packages without any pre-release dependencies.

I'm not sure if @klavs has a workflow for promoting pre-releases, but if not I can promote the above-mentioned alpha to 0.3.1.

**Comment by agent3bood** [comment]
The 0.3.1 did not get published, instead there is an alpha 0.3.2
If you can promote the prerelease then please do it.

**Comment by shyndman** [comment]
Any update on this?

**Comment by smkhalsa** [comment]
Done

**Comment by shyndman** [comment]
Thanks!
