### ISSUE TITLE
Generate types from schema. 

### ISSUE THREAD

**Issue by TarekkMA** [gql-dart/gql#82]
Can the ``schema_builder`` generate code for all types defined in the schema to be used as ``QueryRequest`` instead of making a ``${{queryName}}`` type. Right now a every query has its own return type event if they return the same type.

**Comment by smkhalsa** [comment]
I've moved this issue to the gql package since the code builders live there.

This is an anti-pattern since using a global type would include all fields on that type, not only the fields that you've specified in your query. That said, if you need to use a common type from different queries (to pass into a shared Flutter Widget, for example), you can use a graphql fragment.

**Comment by TarekkMA** [comment]
Okay I will give fragments a try.

For global fields it includes all fields but only the ones that is returned from the query will be set the rest would be null

**Comment by klavs** [comment]
@TarekkMA, semantically there is a difference between `null` and nothing in GraphQL. It is basically like `undefined` in JS, but we do not have it in Dart.

**Comment by TarekkMA** [comment]
@klavs Oh I didn't know that. I'm new to GraphQL ecosystem. If generating types with all fields from schema isn't the norm for GraphQL tools/clients, then I think we can close the issue.

I found fragments can solve this problem of sharing the same type across different components of the program. And I think apollo recommend the use of fragments in this situation.
